baseURL = "https://bemnlam.github.io/"
languageCode = "en-us"
title = "log from home"
theme = "pickles"
publishDir = ".."
# Copyright notice. This is displayer in the footer.
copyright = "&copy; bemnlam"
# custom_css = "/static/css/custom.css"

# Google Analytics API key.
googleAnalytics = "UA-169198494-1"

[markup.goldmark.renderer]
  unsafe= true

[params]
  env = "production"
  paginate = 10
  github = "bemnlam"
  gitlab = "bemnlam"
  linkedin = "hmbenlam"
  # Logo image. This is displayed ogp image.
  logo = "favicon.png"
  favicon = "favicon.ico"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Start blogging in the 2020 lockdown. ğŸ "

[[menu.main]]
    name = "ğŸ“– blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2

[[menu.main]]
    name = "ğŸ· tags"
    url = "/tags"
    weight = 4  
