baseURL = "https://bemnlam.github.io/"
languageCode = "en-us"
title = "log from home"
theme = "pickles"
publishDir = ".."
# Copyright notice. This is displayer in the footer.
copyright = "&copy; bemnlam"
# custom_css = "/static/css/custom.css"

# Google Analytics API key.
googleAnalytics = "UA-169198494-1"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  
  [markup.goldmark.renderer]
    unsafe= true

[params]
  env = "production"
  paginate = 10
  github = "bemnlam"
  gitlab = "bemnlam"
  linkedin = "hmbenlam"
  author = "Bemn"
  authorwebsite = "https://bemnlam.github.io/"
  avatar = "https://gravatar.com/avatar/feded3a7e7501be7a8ce86fd598b2b6a?s=100"
  bio = "A HongKonger."
  # Logo image. This is displayed ogp image.
  logo = "cover.png"
  favicon = "favicon.ico"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "Start blogging in the 2020 lockdown. "
  icon_dark = "ğŸŒŒ"
  icon_light = "ğŸŒ…"

[[menu.main]]
    name = "ğŸ“– blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2

[[menu.main]]
    name = "ğŸ—‚ categories"
    url = "/categories"
    weight = 3

[[menu.main]]
    name = "ğŸ· tags"
    url = "/tags"
    weight = 4
