baseURL = "https://bemnlam.github.io/"
languageCode = "en-us"
title = "dev log"
theme = "pickles"
publishDir = ".."
# Copyright notice. This is displayer in the footer.
copyright = "&copy; bemnlam"
# custom_css = "/static/css/custom.css"

# Google Analytics API key.
# googleAnalytics = "Your Google Analytics tracking id"

[params]
  paginate = 10
  github = "bemnlam"
  # Logo image. This is displayed ogp image.
  logo = "favicon.jpg"
  favicon = "favicon.ico"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "ğŸ“"

[[menu.main]]
    name = "ğŸ“– blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 2

[[menu.main]]
    name = "ğŸ· tags"
    url = "/tags"
    weight = 4  
